/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.courierservice.app;

import com.courierservice.dao.PaketDao;
import com.courierservice.dao.TarifFileDao;
import com.courierservice.model.MasterCourier;
import com.courierservice.model.Paket;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class courierServiceApp extends javax.swing.JFrame {

    List<MasterCourier> kotaTujuan;
    MasterCourier[] kota;
    MasterCourier[] jenisLayanan;
    MasterCourier masCou = new MasterCourier();
    DecimalFormat df = new DecimalFormat("###,###,###.##");
    double hargaPaket;
    //private String indexTipePengiriman;

    /**
     * Creates new form courierServiceApp
     */
    public courierServiceApp() {
        initPaket();
        masCou = new MasterCourier();
        getKota();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asuransiButtonGroup = new javax.swing.ButtonGroup();
        pembayaranButtonGroup = new javax.swing.ButtonGroup();
        hasilDialog = new javax.swing.JDialog();
        selesaiButton = new javax.swing.JButton();
        noPaketHasilLabel = new javax.swing.JLabel();
        pengirimPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaPengirimTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatPengirimTextArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        provinsiPengirimTextField = new javax.swing.JTextField();
        kodePosPengirimTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kotaPengirimTextField = new javax.swing.JTextField();
        submitPengirimButton = new javax.swing.JButton();
        noTelpTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        penerimaPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        namaPenerimaTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatPenerimaTextArea = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        provinsiPenerimaTextField = new javax.swing.JTextField();
        kodePosPenerimaTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        kotaPenerimaTextField = new javax.swing.JTextField();
        submitPenerimaButton = new javax.swing.JButton();
        noTelpPenerimaTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        noPaketTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jenisPaketComboBox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        tanggalKirimDateChooser = new com.toedter.calendar.JDateChooser();
        kotaTujuanComboBox = new javax.swing.JComboBox<>(kotaTujuan.toArray());
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        lTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        beratTextField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        yaRadioButton = new javax.swing.JRadioButton();
        tidakRadioButton = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        hargaBarangTextField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        cashRadioButton = new javax.swing.JRadioButton();
        debitRadioButton = new javax.swing.JRadioButton();
        creditCardRadioButton = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        hargaLabel = new javax.swing.JLabel();
        regulerButton = new javax.swing.JButton();
        kilatButton = new javax.swing.JButton();
        sdsButton = new javax.swing.JButton();
        onsButton = new javax.swing.JButton();
        hdsButton = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        hasilDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        selesaiButton.setText("Selesai");
        selesaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiButtonActionPerformed(evt);
            }
        });

        noPaketHasilLabel.setText("No Paket");

        javax.swing.GroupLayout hasilDialogLayout = new javax.swing.GroupLayout(hasilDialog.getContentPane());
        hasilDialog.getContentPane().setLayout(hasilDialogLayout);
        hasilDialogLayout.setHorizontalGroup(
            hasilDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilDialogLayout.createSequentialGroup()
                .addGroup(hasilDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hasilDialogLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(selesaiButton))
                    .addGroup(hasilDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(noPaketHasilLabel)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        hasilDialogLayout.setVerticalGroup(
            hasilDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noPaketHasilLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(selesaiButton)
                .addGap(43, 43, 43))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pengirimPanel.setBackground(new java.awt.Color(153, 153, 153));
        pengirimPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.black, java.awt.Color.lightGray, java.awt.Color.gray));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PENGIRIM");

        jLabel3.setText("Nama");

        jLabel4.setText("Alamat");

        jLabel5.setText("Kota");

        alamatPengirimTextArea.setColumns(20);
        alamatPengirimTextArea.setRows(5);
        jScrollPane1.setViewportView(alamatPengirimTextArea);

        jLabel7.setText("Provinsi");

        jLabel6.setText("Kode Pos");

        submitPengirimButton.setText("SIMPAN");
        submitPengirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitPengirimButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("No Telepon");

        javax.swing.GroupLayout pengirimPanelLayout = new javax.swing.GroupLayout(pengirimPanel);
        pengirimPanel.setLayout(pengirimPanelLayout);
        pengirimPanelLayout.setHorizontalGroup(
            pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pengirimPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pengirimPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pengirimPanelLayout.createSequentialGroup()
                        .addComponent(submitPengirimButton)
                        .addGap(190, 190, 190))))
            .addGroup(pengirimPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(provinsiPengirimTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodePosPengirimTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTelpTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kotaPengirimTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 60, Short.MAX_VALUE))
        );
        pengirimPanelLayout.setVerticalGroup(
            pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengirimPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodePosPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provinsiPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTelpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitPengirimButton)
                .addGap(22, 22, 22))
        );

        penerimaPanel.setBackground(new java.awt.Color(153, 153, 153));
        penerimaPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.black, java.awt.Color.lightGray, java.awt.Color.gray));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PENERIMA");

        jLabel10.setText("Nama");

        jLabel11.setText("Alamat");

        jLabel12.setText("Kota");

        namaPenerimaTextField.setEnabled(false);

        alamatPenerimaTextArea.setColumns(20);
        alamatPenerimaTextArea.setRows(5);
        alamatPenerimaTextArea.setEnabled(false);
        jScrollPane2.setViewportView(alamatPenerimaTextArea);

        jLabel13.setText("Provinsi");

        provinsiPenerimaTextField.setEnabled(false);

        kodePosPenerimaTextField.setEnabled(false);

        jLabel14.setText("Kode Pos");

        kotaPenerimaTextField.setEnabled(false);

        submitPenerimaButton.setText("SIMPAN");
        submitPenerimaButton.setEnabled(false);
        submitPenerimaButton.setFocusPainted(false);
        submitPenerimaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitPenerimaButtonActionPerformed(evt);
            }
        });

        noTelpPenerimaTextField.setEnabled(false);

        jLabel15.setText("No Telepon");

        javax.swing.GroupLayout penerimaPanelLayout = new javax.swing.GroupLayout(penerimaPanel);
        penerimaPanel.setLayout(penerimaPanelLayout);
        penerimaPanelLayout.setHorizontalGroup(
            penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, penerimaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, penerimaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, penerimaPanelLayout.createSequentialGroup()
                        .addComponent(submitPenerimaButton)
                        .addGap(190, 190, 190))))
            .addGroup(penerimaPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addGap(48, 48, 48)
                .addGroup(penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kotaPenerimaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodePosPenerimaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTelpPenerimaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaPenerimaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(provinsiPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 59, Short.MAX_VALUE))
        );
        penerimaPanelLayout.setVerticalGroup(
            penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penerimaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(namaPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodePosPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provinsiPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTelpPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitPenerimaButton)
                .addGap(22, 22, 22))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("DATA PAKET");

        jLabel16.setText("No Paket");

        noPaketTextField.setEnabled(false);

        jLabel17.setText("Kota Tujuan");

        jLabel18.setText("Jenis Paket");

        jenisPaketComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lain-Lain", "Dokumen", "Elektronik", "Makanan" }));
        jenisPaketComboBox.setEnabled(false);

        jLabel19.setText("Tanggal Kirim");

        tanggalKirimDateChooser.setEnabled(false);

        kotaTujuanComboBox.setEnabled(false);
        kotaTujuanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaTujuanComboBoxActionPerformed(evt);
            }
        });

        jLabel20.setText("Dimensi");

        jLabel21.setText("P :");

        pTextField.setEnabled(false);

        jLabel22.setText("L :");

        lTextField.setEnabled(false);

        jLabel23.setText("T :");

        tTextField.setEnabled(false);

        jLabel24.setText("cm");

        jLabel25.setText("cm");

        jLabel26.setText("cm");

        beratTextField.setEnabled(false);
        beratTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratTextFieldActionPerformed(evt);
            }
        });

        jLabel27.setText("Berat :");

        jLabel28.setText("Kg");

        jLabel30.setText("Asuransi");

        asuransiButtonGroup.add(yaRadioButton);
        yaRadioButton.setText("Ya");
        yaRadioButton.setEnabled(false);
        yaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaRadioButtonActionPerformed(evt);
            }
        });

        asuransiButtonGroup.add(tidakRadioButton);
        tidakRadioButton.setText("Tidak");
        tidakRadioButton.setEnabled(false);
        tidakRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakRadioButtonActionPerformed(evt);
            }
        });

        jLabel31.setText("Harga Barang");

        hargaBarangTextField.setEnabled(false);

        jLabel32.setText("Pembayaran");

        pembayaranButtonGroup.add(cashRadioButton);
        cashRadioButton.setText("Cash");
        cashRadioButton.setEnabled(false);

        pembayaranButtonGroup.add(debitRadioButton);
        debitRadioButton.setText("Debit");
        debitRadioButton.setEnabled(false);

        pembayaranButtonGroup.add(creditCardRadioButton);
        creditCardRadioButton.setText("Credit Card");
        creditCardRadioButton.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tanggalKirimDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(jenisPaketComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kotaTujuanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(beratTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(338, 338, 338)
                            .addComponent(jLabel20)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel16)
                            .addGap(388, 388, 388)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(yaRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tidakRadioButton))
                    .addComponent(hargaBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cashRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(debitRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(creditCardRadioButton)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(noPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(pTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(lTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel30)
                            .addComponent(yaRadioButton)
                            .addComponent(tidakRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(tTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel31)
                            .addComponent(hargaBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(beratTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel32)
                            .addComponent(cashRadioButton)
                            .addComponent(debitRadioButton)
                            .addComponent(creditCardRadioButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(kotaTujuanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jenisPaketComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(tanggalKirimDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel33.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel33.setText("PAKET");

        hargaLabel.setText("Total Tarif");

        regulerButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        regulerButton.setText("REGULER");
        regulerButton.setEnabled(false);
        regulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regulerButtonActionPerformed(evt);
            }
        });

        kilatButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kilatButton.setText("KILAT");
        kilatButton.setEnabled(false);
        kilatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilatButtonActionPerformed(evt);
            }
        });

        sdsButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sdsButton.setText("SDS");
        sdsButton.setEnabled(false);
        sdsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdsButtonActionPerformed(evt);
            }
        });

        onsButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        onsButton.setText("ONS");
        onsButton.setEnabled(false);
        onsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onsButtonActionPerformed(evt);
            }
        });

        hdsButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hdsButton.setText("HDS");
        hdsButton.setEnabled(false);
        hdsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdsButtonActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("PILIH JENIS LAYANAN");

        jMenu3.setText("Menu");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pengirimPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(penerimaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel33)
                        .addGap(410, 410, 410))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(regulerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kilatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sdsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(onsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hdsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(hargaLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pengirimPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(penerimaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regulerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hdsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kilatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaLabel)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beratTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratTextFieldActionPerformed

    private void regulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regulerButtonActionPerformed

        if (yaRadioButton.isSelected()) {

            Paket pak = new Paket();
            PaketDao pd = new PaketDao();
            String kotaTuj = String.valueOf(kotaTujuanComboBox.getSelectedItem());
            String beratStr = beratTextField.getText();
            String hargaStr = hargaBarangTextField.getText();
            double harga = Double.parseDouble(hargaStr);

            int berat = Integer.parseInt(beratStr);

            pak.setHargaBarang(harga);
            double hargaAsuransi = pak.getaAsuransi();

            masCou = pd.hitungBiaya(kotaTuj, berat);
            hargaPaket = masCou.getReguler() + hargaAsuransi;

            hargaLabel.setText("Rp " + df.format(hargaPaket));

            hasilDialog.dispose();
            hasilDialog.setVisible(true);
            noPaketHasilLabel.setText("Rp " + df.format(hargaPaket));

        } else {

            PaketDao pd = new PaketDao();
            String kotaTuj = String.valueOf(kotaTujuanComboBox.getSelectedItem());
            String beratStr = beratTextField.getText();

            int berat = Integer.parseInt(beratStr);
            masCou = pd.hitungBiaya(kotaTuj, berat);

            hargaLabel.setText("Rp " + df.format(masCou.getReguler()));
        }
        //System.out.println("Harga = " + masCou.hargaReguler());

        //if(jenisLayananComboBox.getSelectedItem())
    }//GEN-LAST:event_regulerButtonActionPerformed

    private void kotaTujuanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaTujuanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kotaTujuanComboBoxActionPerformed

    private void kilatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilatButtonActionPerformed
        // TODO add your handling code here:
        if (yaRadioButton.isSelected()) {

            Paket pak = new Paket();
            PaketDao pd = new PaketDao();
            String kotaTuj = String.valueOf(kotaTujuanComboBox.getSelectedItem());
            String beratStr = beratTextField.getText();
            String hargaStr = hargaBarangTextField.getText();
            double harga = Double.parseDouble(hargaStr);

            int berat = Integer.parseInt(beratStr);

            pak.setHargaBarang(harga);
            double hargaAsuransi = pak.getaAsuransi();

            masCou = pd.hitungBiaya(kotaTuj, berat);

            hargaLabel.setText("Rp " + df.format((masCou.getKilat() + hargaAsuransi)));

        } else {

            PaketDao pd = new PaketDao();
            String kotaTuj = String.valueOf(kotaTujuanComboBox.getSelectedItem());
            String beratStr = beratTextField.getText();

            int berat = Integer.parseInt(beratStr);
            masCou = pd.hitungBiaya(kotaTuj, berat);

            hargaLabel.setText("Rp " + df.format(masCou.getKilat()));
        }

    }//GEN-LAST:event_kilatButtonActionPerformed

    private void sdsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdsButtonActionPerformed
        // TODO add your handling code here:
        if (yaRadioButton.isSelected()) {

            Paket pak = new Paket();
            PaketDao pd = new PaketDao();
            String kotaTuj = String.valueOf(kotaTujuanComboBox.getSelectedItem());
            String beratStr = beratTextField.getText();
            String hargaStr = hargaBarangTextField.getText();
            double harga = Double.parseDouble(hargaStr);

            int berat = Integer.parseInt(beratStr);

            pak.setHargaBarang(harga);
            double hargaAsuransi = pak.getaAsuransi();

            masCou = pd.hitungBiaya(kotaTuj, berat);

            hargaLabel.setText("Rp " + df.format((masCou.getSds() + hargaAsuransi)));

        } else {

            PaketDao pd = new PaketDao();
            String kotaTuj = String.valueOf(kotaTujuanComboBox.getSelectedItem());
            String beratStr = beratTextField.getText();

            int berat = Integer.parseInt(beratStr);
            masCou = pd.hitungBiaya(kotaTuj, berat);

            hargaLabel.setText("Rp " + df.format(masCou.getSds()));
        }
    }//GEN-LAST:event_sdsButtonActionPerformed

    private void onsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onsButtonActionPerformed
        if (yaRadioButton.isSelected()) {

            Paket pak = new Paket();
            PaketDao pd = new PaketDao();
            String kotaTuj = String.valueOf(kotaTujuanComboBox.getSelectedItem());
            String beratStr = beratTextField.getText();
            String hargaStr = hargaBarangTextField.getText();
            double harga = Double.parseDouble(hargaStr);

            int berat = Integer.parseInt(beratStr);

            pak.setHargaBarang(harga);
            double hargaAsuransi = pak.getaAsuransi();

            masCou = pd.hitungBiaya(kotaTuj, berat);

            hargaLabel.setText("Rp " + df.format((masCou.getOns() + hargaAsuransi)));

        } else {

            PaketDao pd = new PaketDao();
            String kotaTuj = String.valueOf(kotaTujuanComboBox.getSelectedItem());
            String beratStr = beratTextField.getText();

            int berat = Integer.parseInt(beratStr);
            masCou = pd.hitungBiaya(kotaTuj, berat);

            hargaLabel.setText("Rp " + df.format(masCou.getOns()));
        }

    }//GEN-LAST:event_onsButtonActionPerformed

    private void hdsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdsButtonActionPerformed
        if (yaRadioButton.isSelected()) {

            Paket pak = new Paket();
            PaketDao pd = new PaketDao();
            String kotaTuj = String.valueOf(kotaTujuanComboBox.getSelectedItem());
            String beratStr = beratTextField.getText();
            String hargaStr = hargaBarangTextField.getText();
            double harga = Double.parseDouble(hargaStr);

            int berat = Integer.parseInt(beratStr);

            pak.setHargaBarang(harga);
            double hargaAsuransi = pak.getaAsuransi();

            masCou = pd.hitungBiaya(kotaTuj, berat);

            hargaLabel.setText("Rp " + df.format((masCou.getHds() + hargaAsuransi)));

        } else {

            PaketDao pd = new PaketDao();
            String kotaTuj = String.valueOf(kotaTujuanComboBox.getSelectedItem());
            String beratStr = beratTextField.getText();

            int berat = Integer.parseInt(beratStr);
            masCou = pd.hitungBiaya(kotaTuj, berat);

            hargaLabel.setText("Rp " + df.format(masCou.getHds()));
        }

    }//GEN-LAST:event_hdsButtonActionPerformed

    private void yaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaRadioButtonActionPerformed
        // TODO add your handling code here:
        hargaBarangTextField.setEnabled(true);
    }//GEN-LAST:event_yaRadioButtonActionPerformed

    private void tidakRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakRadioButtonActionPerformed
        // TODO add your handling code here:
        hargaBarangTextField.setEnabled(false);
    }//GEN-LAST:event_tidakRadioButtonActionPerformed

    private void submitPengirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitPengirimButtonActionPerformed
        // TODO add your handling code here:
        if (namaPengirimTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Nama Pengirim");
        } else if (alamatPengirimTextArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Dulu Alamat Pengirim");
        } else if (kodePosPengirimTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Kode Pos Pengirim");
        } else if (kotaPengirimTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Kota Pengirim");
        } else if (kotaPengirimTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Provinsi Pengirim");
        } else if (noTelpTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Notelp Pengirim");
        } else {

            JOptionPane.showMessageDialog(null, "Data Telah Ditambah");
            namaPengirimTextField.setEnabled(false);
            alamatPengirimTextArea.setEnabled(false);
            kodePosPengirimTextField.setEnabled(false);
            kotaPengirimTextField.setEnabled(false);
            provinsiPengirimTextField.setEnabled(false);
            noTelpTextField.setEnabled(false);
            submitPengirimButton.setEnabled(false);
            namaPenerimaTextField.setEnabled(true);
            alamatPenerimaTextArea.setEnabled(true);
            kodePosPenerimaTextField.setEnabled(true);
            kotaPenerimaTextField.setEnabled(true);
            provinsiPenerimaTextField.setEnabled(true);
            noTelpPenerimaTextField.setEnabled(true);
            submitPenerimaButton.setEnabled(true);
        }
    }//GEN-LAST:event_submitPengirimButtonActionPerformed

    private void submitPenerimaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitPenerimaButtonActionPerformed
        // TODO add your handling code here:
        if (namaPenerimaTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Nama Penerima");
        } else if (alamatPenerimaTextArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Dulu Alamat Penerima");
        } else if (kodePosPenerimaTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Kode Pos Penerima");
        } else if (kotaPenerimaTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Kota Penerima");
        } else if (kotaPenerimaTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Provinsi Penerima");
        } else if (noTelpPenerimaTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Notelp Penerima");
        } else {

            JOptionPane.showMessageDialog(null, "Data Telah Ditambah");
            namaPenerimaTextField.setEnabled(false);
            alamatPenerimaTextArea.setEnabled(false);
            kodePosPenerimaTextField.setEnabled(false);
            kotaPenerimaTextField.setEnabled(false);
            provinsiPenerimaTextField.setEnabled(false);
            noTelpPenerimaTextField.setEnabled(false);
            submitPenerimaButton.setEnabled(false);

            noPaketTextField.setEnabled(true);
            kotaTujuanComboBox.setEnabled(true);
            jenisPaketComboBox.setEnabled(true);
            tanggalKirimDateChooser.setEnabled(true);
            pTextField.setEnabled(true);
            lTextField.setEnabled(true);
            tTextField.setEnabled(true);
            beratTextField.setEnabled(true);
            yaRadioButton.setEnabled(true);
            tidakRadioButton.setEnabled(true);
            hargaBarangTextField.setEnabled(true);
            cashRadioButton.setEnabled(true);
            debitRadioButton.setEnabled(true);
            creditCardRadioButton.setEnabled(true);

            regulerButton.setEnabled(true);
            kilatButton.setEnabled(true);
            sdsButton.setEnabled(true);
            onsButton.setEnabled(true);
            hdsButton.setEnabled(true);
            hargaBarangTextField.setEnabled(false);
        }

    }//GEN-LAST:event_submitPenerimaButtonActionPerformed

    private void selesaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiButtonActionPerformed

        System.exit(0);

    }//GEN-LAST:event_selesaiButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(courierServiceApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(courierServiceApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(courierServiceApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(courierServiceApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new courierServiceApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatPenerimaTextArea;
    private javax.swing.JTextArea alamatPengirimTextArea;
    private javax.swing.ButtonGroup asuransiButtonGroup;
    private javax.swing.JTextField beratTextField;
    private javax.swing.JRadioButton cashRadioButton;
    private javax.swing.JRadioButton creditCardRadioButton;
    private javax.swing.JRadioButton debitRadioButton;
    private javax.swing.JTextField hargaBarangTextField;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JDialog hasilDialog;
    private javax.swing.JButton hdsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenisPaketComboBox;
    private javax.swing.JButton kilatButton;
    private javax.swing.JTextField kodePosPenerimaTextField;
    private javax.swing.JTextField kodePosPengirimTextField;
    private javax.swing.JTextField kotaPenerimaTextField;
    private javax.swing.JTextField kotaPengirimTextField;
    private javax.swing.JComboBox<Object> kotaTujuanComboBox;
    private javax.swing.JTextField lTextField;
    private javax.swing.JTextField namaPenerimaTextField;
    private javax.swing.JTextField namaPengirimTextField;
    private javax.swing.JLabel noPaketHasilLabel;
    private javax.swing.JTextField noPaketTextField;
    private javax.swing.JTextField noTelpPenerimaTextField;
    private javax.swing.JTextField noTelpTextField;
    private javax.swing.JButton onsButton;
    private javax.swing.JTextField pTextField;
    private javax.swing.ButtonGroup pembayaranButtonGroup;
    private javax.swing.JPanel penerimaPanel;
    private javax.swing.JPanel pengirimPanel;
    private javax.swing.JTextField provinsiPenerimaTextField;
    private javax.swing.JTextField provinsiPengirimTextField;
    private javax.swing.JButton regulerButton;
    private javax.swing.JButton sdsButton;
    private javax.swing.JButton selesaiButton;
    private javax.swing.JButton submitPenerimaButton;
    private javax.swing.JButton submitPengirimButton;
    private javax.swing.JTextField tTextField;
    private com.toedter.calendar.JDateChooser tanggalKirimDateChooser;
    private javax.swing.JRadioButton tidakRadioButton;
    private javax.swing.JRadioButton yaRadioButton;
    // End of variables declaration//GEN-END:variables

    public void initPaket() {

        kotaTujuan = TarifFileDao.kotaPaket();

    }

//    public void initLayanan() {
//        
//    }
    public MasterCourier[] getKota() {
        int size = kotaTujuan.size();
        kota = new MasterCourier[size];

        for (int i = 0; i < size; i++) {
            MasterCourier mc = kotaTujuan.get(i);
        }
        return kota;
    }

//    public MasterCourier[] getLayanan() {
//        int size = 
//    
//    }
}
